import type { SquadPlayerResearch } from './researchData';

type SquadLine = [string, string[]];

const PLAYER_CN: Record<string, string> = {
  'Alisson': '阿利森',
  'Ederson': '埃德森',
  'Weverton': '韦弗顿',
  'Gabriel Magalhaes': '加布里埃尔',
  'Marquinhos': '马尔基尼奥斯',
  'Danilo': '达尼洛',
  'Bremer': '布雷默',
  'Casemiro': '卡塞米罗',
  'Fabinho': '法比尼奥',
  'Lucas Paqueta': '卢卡斯·帕奎塔',
  'Raphinha': '拉菲尼亚',
  'Neymar': '内马尔',
  'Vinicius Junior': '维尼修斯',
  'Endrick': '恩德里克',
  'Kylian Mbappe': '姆巴佩',
  'Ousmane Dembele': '登贝莱',
  'N’Golo Kante': '坎特',
  'Adrien Rabiot': '拉比奥',
  'Aurelien Tchouameni': '楚阿梅尼',
  'William Saliba': '萨利巴',
  'Jules Kounde': '孔德',
  'Theo Hernandez': '特奥·埃尔南德斯',
  'Mike Maignan': '迈尼昂',
  'Marcus Thuram': '小图拉姆',
  'Harry Kane': '哈里·凯恩',
  'Bukayo Saka': '萨卡',
  'Jude Bellingham': '贝林厄姆',
  'Declan Rice': '赖斯',
  'Jordan Pickford': '皮克福德',
  'John Stones': '斯通斯',
  'Reece James': '里斯·詹姆斯',
  'Marcus Rashford': '拉什福德',
  'Manuel Neuer': '诺伊尔',
  'Joshua Kimmich': '基米希',
  'Antonio Rudiger': '吕迪格',
  'Jamal Musiala': '穆西亚拉',
  'Florian Wirtz': '维尔茨',
  'Kai Havertz': '哈弗茨',
  'Leroy Sane': '萨内',
  'Thibaut Courtois': '库尔图瓦',
  'Kevin De Bruyne': '德布劳内',
  'Romelu Lukaku': '卢卡库',
  'Jeremy Doku': '多库',
  'Youri Tielemans': '蒂勒曼斯',
  'Virgil van Dijk': '范戴克',
  'Frenkie de Jong': '弗朗基·德容',
  'Cody Gakpo': '加克波',
  'Memphis Depay': '德佩',
  'Denzel Dumfries': '邓弗里斯',
  'Pedri': '佩德里',
  'Gavi': '加维',
  'Rodri': '罗德里',
  'Lamine Yamal': '亚马尔',
  'Dani Olmo': '奥尔莫',
  'Nico Williams': '尼科·威廉姆斯',
  'Unai Simon': '乌奈·西蒙',
  'David Raya': '大卫·拉亚',
  'Achraf Hakimi': '阿什拉夫',
  'Yassine Bounou': '布努',
  'Sofyan Amrabat': '阿姆拉巴特',
  'Brahim Díaz': '布拉欣·迪亚斯',
  'Ayoub El Kaabi': '恩内斯里',
  'Takefusa Kubo': '久保建英',
  'Kubo Takefusa': '久保建英',
  'Endo Wataru': '远藤航',
  'Kamada Daichi': '镰田大地',
  'Tomiyasu Takehiro': '富安健洋',
  'Ito Junya': '伊东纯也',
  'Doan Ritsu': '堂安律',
  'Erling Haaland': '哈兰德',
  'Martin Odegaard': '厄德高',
  'Alexander Sorloth': '索尔洛特',
  'Christian Pulisic': '普利西奇',
  'Weston McKennie': '麦肯尼',
  'Tyler Adams': '泰勒·亚当斯',
  'Gio Reyna': '雷纳',
  'Tim Weah': '蒂莫西·维阿',
  'Sergino Dest': '德斯特',
  'David Alaba': '阿拉巴',
  'Marko Arnautovic': '阿瑙托维奇',
  'Marcel Sabitzer': '萨比策',
  'Konrad Laimer': '莱默尔',
  'Edin Dzeko': '哲科',
  'Sead Kolasinac': '科拉希纳茨',
};

export const STAR_PLAYER_PRIORITY: Record<string, number> = {
  'Lionel Messi': 100,
  'Kylian Mbappe': 99,
  'Erling Haaland': 98,
  'Jude Bellingham': 97,
  'Vinicius Junior': 96,
  'Harry Kane': 95,
  'Lamine Yamal': 94,
  'Kevin De Bruyne': 93,
  'Florian Wirtz': 92,
  'Jamal Musiala': 91,
  'Pedri': 90,
  'Rodri': 89,
  'Bukayo Saka': 88,
  'Neymar': 87,
  'Raphinha': 86,
  'Ousmane Dembele': 85,
  'Virgil van Dijk': 84,
  'Frenkie de Jong': 83,
  'Cody Gakpo': 82,
  'Bruno Guimaraes': 81,
  'Casemiro': 80,
  'Marquinhos': 79,
  'Alisson': 78,
  'Ederson': 77,
  'Endrick': 76,
  'Michael Olise': 75,
  'Aurelien Tchouameni': 74,
  'William Saliba': 73,
  'Mike Maignan': 72,
  'Theo Hernandez': 71,
  'N’Golo Kante': 70,
  'Jules Kounde': 69,
  'Marcus Thuram': 68,
  'Declan Rice': 67,
  'Jordan Pickford': 66,
  'John Stones': 65,
  'Reece James': 64,
  'Marcus Rashford': 63,
  'Kai Havertz': 62,
  'Joshua Kimmich': 61,
  'Antonio Rudiger': 60,
  'Manuel Neuer': 59,
  'Leroy Sane': 58,
  'Thibaut Courtois': 57,
  'Romelu Lukaku': 56,
  'Jeremy Doku': 55,
  'Achraf Hakimi': 54,
  'Yassine Bounou': 53,
  'Sofyan Amrabat': 52,
  'Brahim Díaz': 51,
  'Takefusa Kubo': 50,
  'Kubo Takefusa': 50,
  'Endo Wataru': 49,
  'Tomiyasu Takehiro': 48,
  'Ito Junya': 47,
  'Doan Ritsu': 46,
  'Martin Odegaard': 45,
  'Alexander Sorloth': 44,
  'Christian Pulisic': 43,
  'Weston McKennie': 42,
  'Gio Reyna': 41,
  'Sergino Dest': 40,
  'David Alaba': 39,
  'Marcel Sabitzer': 38,
  'Edin Dzeko': 37,
};

const parsePlayer = (raw: string, position: string, number: number): SquadPlayerResearch => {
  const match = raw.match(/^(.*?)\s*\((.*?)\)$/);
  const englishName = (match?.[1] || raw).trim();
  return {
    name: PLAYER_CN[englishName] || englishName,
    englishName,
    club: match?.[2]?.trim(),
    position,
    number,
    status: '官方'
  };
};

const buildSquad = (lines: SquadLine[]): SquadPlayerResearch[] => {
  let number = 1;
  return lines.flatMap(([position, players]) => (
    players.map(player => parsePlayer(player, position, number++))
  ));
};

export const CONFIRMED_COACHES: Record<string, string> = {
  argentina: '斯卡洛尼',
  austria: '朗尼克',
  belgium: '鲁迪·加西亚',
  bosnia: '巴巴雷兹',
  brazil: '安切洛蒂',
  cape_verde: 'Bubista',
  colombia: '内斯托尔·洛伦索',
  curacao: '艾德沃卡特',
  dr_congo: '德萨布尔',
  england: '图赫尔',
  france: '德尚',
  germany: '纳格尔斯曼',
  haiti: '米涅',
  ivory_coast: '埃梅尔斯·法埃',
  japan: '森保一',
  morocco: '雷格拉吉',
  netherlands: '罗纳德·科曼',
  new_zealand: '达伦·巴兹利',
  norway: '索尔巴肯',
  scotland: '史蒂夫·克拉克',
  senegal: '帕普·蒂奥',
  south_korea: '洪明甫',
  spain: '德拉富恩特',
  sweden: '托马森',
  switzerland: '穆拉特·雅金',
  tunisia: '萨米·特拉贝尔西',
  usa: '波切蒂诺',
  mexico: '阿吉雷',
  south_africa: '雨果·布罗斯',
  qatar: '洛佩特吉',
  iran: '加莱诺伊',
  iraq: '格雷厄姆·阿诺德',
  ghana: '奎罗斯',
  uzbekistan: '卡纳瓦罗',
};

export const CONFIRMED_SQUADS: Record<string, SquadPlayerResearch[]> = {
  austria: buildSquad([
    ['门将', ['Patrick Pentz (Brondby IF)', 'Alexander Schlager (RB Salzburg)', 'Florian Wiegele (Viktoria Plzeň)']],
    ['后卫', ['David Affengruber (Elche)', 'David Alaba (Real Madrid)', 'Kevin Danso (Tottenham Hotspur)', 'Marco Friedl (Werder Bremen)', 'Philipp Lienhart (SC Freiburg)', 'Phillipp Mwene (Mainz 05)', 'Stefan Posch (Mainz 05)', 'Alexander Prass (TSG Hoffenheim)', 'Michael Svoboda (Venezia)']],
    ['中场', ['Christoph Baumgartner (RB Leipzig)', 'Carney Chukwuemeka (Borussia Dortmund)', 'Florian Grillitsch (SC Braga)', 'Konrad Laimer (Bayern München)', 'Marcel Sabitzer (Borussia Dortmund)', 'Xaver Schlager (RB Leipzig)', 'Nicolas Seiwald (RB Leipzig)', 'Romano Schmid (Werder Bremen)', 'Alessandro Schöpf (Wolfsberger AC)', 'Paul Wanner (PSV Eindhoven)', 'Patrick Wimmer (VfL Wolfsburg)']],
    ['前锋', ['Marko Arnautovic (Crvena Zvezda)', 'Michael Gregoritsch (Augsburg)', 'Sasa Kalajdzic (LASK)']],
  ]),
  belgium: buildSquad([
    ['门将', ['Thibaut Courtois (Real Madrid)', 'Senne Lammens (Manchester United)', 'Mike Penders (Strasbourg)']],
    ['后卫', ['Timothy Castagne (Fulham)', 'Zeno Debast (Sporting CP)', 'Maxim De Cuyper (Brighton)', 'Koni De Winter (AC Milan)', 'Brandon Mechele (Club Brugge)', 'Thomas Meunier (Lille)', 'Nathan Ngoy (Lille)', 'Joaquin Seys (Club Brugge)', 'Arthur Theate (Eintracht Frankfurt)']],
    ['中场', ['Kevin De Bruyne (Napoli)', 'Amadou Onana (Aston Villa)', 'Nicolas Raskin (Rangers)', 'Youri Tielemans (Aston Villa)', 'Hans Vanaken (Club Brugge)', 'Axel Witsel (Girona)']],
    ['前锋', ['Charles De Ketelaere (Atalanta)', 'Jeremy Doku (Manchester City)', 'Matias Fernandez Pardo (Lille)', 'Romelu Lukaku (Napoli)', 'Dodi Lukebakio (Benfica)', 'Diego Moreira (Strasbourg)', 'Alexis Saelemaekers (AC Milan)', 'Leandro Trossard (Arsenal)']],
  ]),
  bosnia: buildSquad([
    ['门将', ['Nikola Vasilj (FC St. Pauli)', 'Martin Zlomislic (HNK Rijeka)', 'Osman Hadzikic (Slaven Belupo)']],
    ['后卫', ['Sead Kolasinac (Atalanta BC)', 'Amar Dedic (SL Benfica)', 'Nihad Mujakic (Gaziantep FK)', 'Nikola Katic (Schalke 04)', 'Tarik Muharemovic (US Sassuolo)', 'Stjepan Radeljic (HNK Rijeka)', 'Dennis Hadzikadunic (UC Sampdoria)', 'Nidal Celik (Lens)']],
    ['中场', ['Amir Hadžiahmetović (Hull City)', 'Ivan Sunjic (Pafos FC)', 'Ivan Basic (FC Astana)', 'Dzenis Burnic (Karlsruher SC)', 'Ermin Mahmic (FC Slovan Liberec)', 'Benjamin Tahirovic (Brondby IF)', 'Amar Memic (FC Viktoria Plzen)', 'Armin Gigovic (BSC Young Boys)']],
    ['前锋', ['Kerim Alajbegovic (RB Salzburg)', 'Esmir Bajraktarevic (PSV Eindhoven)', 'Ermedin Demirović (VfB Stuttgart)', 'Jovo Lukic (FC Universitatea Cluj)', 'Samed Bazdar (Jagiellonia Bialystok)', 'Haris Tabakovic (Borussia Monchengladbach)', 'Edin Dzeko (Schalke 04)']],
  ]),
  brazil: buildSquad([
    ['门将', ['Alisson (Liverpool)', 'Ederson (Fenerbahce)', 'Weverton (Gremio)']],
    ['后卫', ['Wesley (Roma)', 'Douglas Santos (Zenit)', 'Alex Sandro (Flamengo)', 'Gabriel Magalhaes (Arsenal)', 'Marquinhos (PSG)', 'Danilo (Flamengo)', 'Bremer (Juventus)', 'Ibanez (Al-Ahli)', 'Leo Pereira (Flamengo)']],
    ['中场', ['Bruno Guimaraes (Newcastle)', 'Casemiro (Manchester United)', 'Danilo Santos (Botafogo)', 'Fabinho (Al-Ittihad)', 'Lucas Paqueta (Flamengo)', 'Raphinha (Barcelona)', 'Neymar (Santos)']],
    ['前锋', ['Vinicius Junior (Real Madrid)', 'Luiz Henrique (Zenit)', 'Matheus Cunha (Manchester United)', 'Gabriel Martinelli (Arsenal)', 'Igor Thiago (Brentford)', 'Endrick (Lyon)', 'Rayan (Bournemouth)']],
  ]),
  france: buildSquad([
    ['门将', ['Mike Maignan (AC Milan)', 'Brice Samba (Rennes)', 'Robin Risser (Lens)']],
    ['后卫', ['Dayot Upamecano (Bayern Munich)', 'William Saliba (Arsenal)', 'Lucas Digne (Aston Villa)', 'Theo Hernandez (Al-Hilal)', 'Lucas Hernandez (PSG)', 'Ibrahima Konate (Liverpool)', 'Jules Kounde (Barcelona)', 'Malo Gusto (Chelsea)', 'Maxence Lacroix (Crystal Palace)']],
    ['中场', ['N’Golo Kante (Fenerbahce)', 'Adrien Rabiot (AC Milan)', 'Manu Kone (Roma)', 'Aurelien Tchouameni (Real Madrid)', 'Warren Zaire-Emery (PSG)']],
    ['前锋', ['Maghnes Akliouche (Monaco)', 'Kylian Mbappe (Real Madrid)', 'Ousmane Dembele (PSG)', 'Michael Olise (Bayern Munich)', 'Desire Doue (PSG)', 'Bradley Barcola (PSG)', 'Rayan Cherki (Manchester City)', 'Marcus Thuram (Inter Milan)', 'Jean-Philippe Mateta (Crystal Palace)']],
  ]),
  england: buildSquad([
    ['门将', ['Jordan Pickford (Everton)', 'Dean Henderson (Crystal Palace)', 'James Trafford (Manchester City)']],
    ['后卫', ['Reece James (Chelsea)', 'Tino Livramento (Newcastle)', 'Marc Guehi (Manchester City)', 'Ezri Konsa (Aston Villa)', 'John Stones (Manchester City)', 'Jarell Quansah (Bayer Leverkusen)', 'Nico O’Reilly (Manchester City)', 'Dan Burn (Newcastle)', 'Djed Spence (Tottenham Hotspur)']],
    ['中场', ['Declan Rice (Arsenal)', 'Elliot Anderson (Nottingham Forest)', 'Jude Bellingham (Real Madrid)', 'Jordan Henderson (Brentford)', 'Morgan Rogers (Aston Villa)', 'Kobbie Mainoo (Manchester United)', 'Eberechi Eze (Arsenal)']],
    ['前锋', ['Harry Kane (Bayern Munich)', 'Ivan Toney (Al-Ahli)', 'Ollie Watkins (Aston Villa)', 'Bukayo Saka (Arsenal)', 'Noni Madueke (Arsenal)', 'Marcus Rashford (Barcelona)', 'Anthony Gordon (Newcastle)']],
  ]),
  germany: buildSquad([
    ['门将', ['Oliver Baumann (Hoffenheim)', 'Manuel Neuer (Bayern Munich)', 'Alexander Nubel (Monaco)']],
    ['后卫', ['Waldemar Anton (Borussia Dortmund)', 'Nathaniel Brown (Frankfurt)', 'Joshua Kimmich (Bayern Munich)', 'David Raum (RB Leipzig)', 'Antonio Rudiger (Real Madrid)', 'Nico Schlotterbeck (Borussia Dortmund)', 'Jonathan Tah (Bayern Munich)', 'Malick Thiaw (Newcastle)']],
    ['中场', ['Nadiem Amiri (Mainz)', 'Leon Goretzka (Bayern Munich)', 'Pascal Gross (Brighton)', 'Jamie Leweling (Stuttgart)', 'Lennart Karl (Bayern Munich)', 'Jamal Musiala (Bayern Munich)', 'Felix Nmecha (Borussia Dortmund)', 'Alexander Pavlovic (Bayern Munich)', 'Angelo Stiller (Stuttgart)', 'Florian Wirtz (Liverpool)']],
    ['前锋', ['Maximilian Beier (Borussia Dortmund)', 'Kai Havertz (Arsenal)', 'Leroy Sane (Galatasaray)', 'Denis Undav (Stuttgart)', 'Nick Woltemade (Newcastle)']],
  ]),
  haiti: buildSquad([
    ['门将', ['Johnny Placide (SC Bastia)', 'Alexandre Pierre (FC Sochaux)', 'Josue Duverger (FC Cosmos Koblenz)']],
    ['后卫', ['Carlens Arcus (Angers SCO)', 'Wilguens Paugain (SV Zulte Waregem)', 'Duke Lacroix (Colorado Springs)', 'Martin Experience (AS Nancy-Lorraine)', 'Jean-Kevin Duverne (KAA Gent)', 'Ricardo Ade (LDU Quito)', 'Hannes Delcroix (FC Lugano)', 'Keeto Thermoncy (BSC Young Boys II)']],
    ['中场', ['Leverton Pierre (FC Vizela)', 'Carl-Fred Sainthe (El Paso Locomotive FC)', 'Jean-Jacques Danley (Philadelphia Union)', 'Jeanricner Bellegarde (Wolverhampton)', 'Pierre Woodenski (Violette AC)', 'Dominique Simon (FC Tatran Presov)']],
    ['前锋', ['Louicius Deedson (FC Dallas)', 'Ruben Providence (Almere City FC)', 'Josue Casimir (AJ Auxerre)', 'Derrick Etienne (Toronto FC)', 'Wilson Isidor (Sunderland AFC)', 'Duckens Nazon (Esteghlal FC)', 'Frantzdy Pierrot (Caykur Rizespor)', 'Yassin Fortune (FC Vizela)', 'Lenny Joseph (Ferencvaros TC)']],
  ]),
  japan: buildSquad([
    ['门将', ['Hayakawa Tomoki (Kashima Antlers)', 'Suzuki Zion (Parma)', 'Osako Keisuke (Sanfrecce Hiroshima)']],
    ['后卫', ['Nagatomo Yuto (FC Tokyo)', 'Taniguchi Shogo (Sint-Truiden)', 'Tomiyasu Takehiro (Ajax)', 'Itakura Ko (Ajax)', 'Watanabe Tsuyoshi (Feyenoord)', 'Ito Hiroki (Bayern Munich)', 'Suzuki Junnosuke (København)', 'Seko Ayumu (Le Havre)', 'Sugawara Yukinari (Werder Bremen)']],
    ['中场', ['Kamada Daichi (Crystal Palace)', 'Sano Kaishu (Mainz)', 'Tanaka Ao (Leeds United)', 'Endo Wataru (Liverpool)', 'Nakamura Keito (Reims)', 'Doan Ritsu (Eintracht Frankfurt)']],
    ['前锋', ['Ito Junya (Genk)', 'Kubo Takefusa (Real Sociedad)', 'Suzuki Yuito (Freiburg)', 'Ueda Ayase (Feyenoord)', 'Ogawa Koki (Nijmegen)', 'Maeda Daizen (Celtic)', 'Shiogai Kento (Wolfsburg)', 'Goto Keisuke (Sint-Truiden)']],
  ]),
  morocco: buildSquad([
    ['门将', ['Yassine Bounou (Al Hilal)', 'Munir El Kajoui (RS Berkane)', 'Ahmed Reda Tagnaouti (AS FAR)']],
    ['后卫', ['Noussair Mazraoui (Manchester United)', 'Anass Salah-Eddine (PSV Eindhoven)', 'Youssef Belammari (Al Ahly)', 'Nayef Aguerd (Olympique de Marseille)', 'Chadi Riad (Crystal Palace)', 'Issa Diop (Fulham)', 'Redouane Halhal (Mechelen)', 'Achraf Hakimi (PSG)', 'Zakaria El Ouahdi (Genk)']],
    ['中场', ['Samir El Mourabet (Strasbourg)', 'Ayyoub Bouaddi (Lille)', 'Neil El Aynaoui (AS Roma)', 'Sofyan Amrabat (Real Betis)', 'Azzedine Ounahi (Girone)', 'Bilal El Khannouss (Stuttgart)', 'Ismael Saibari (PSV Eindhoven)']],
    ['前锋', ['Abdessamad Ezzalzouli (Real Betis)', 'Chemsdine Talbi (Sunderland)', 'Soufiane Rahimi (Al Ain)', 'Ayoub El Kaabi (Olympiacos)', 'Brahim Díaz (Real Madrid)', 'Yassine Gessime (Strasbourg)', 'Ayoube Amaimouni (Eintracht Frankfurt)']],
  ]),
  netherlands: buildSquad([
    ['门将', ['Mark Flekken (Bayer Leverkusen)', 'Robin Roefs (Sunderland)', 'Bart Verbruggen (Brighton & Hove Albion)']],
    ['后卫', ['Nathan Ake (Manchester City)', 'Jorrel Hato (Chelsea)', 'Denzel Dumfries (Inter Milan)', 'Jurrien Timber (Arsenal)', 'John Paul van Hecke (Brighton & Hove Albion)', 'Micky van de Ven (Tottenham Hotspur)', 'Virgil van Dijk (Liverpool)']],
    ['中场', ['Frenkie de Jong (Barcelona)', 'Marten de Roon (Atalanta)', 'Ryan Gravenberch (Liverpool)', 'Teun Koopmeiners (Juventus)', 'Noa Lang (Galatasaray)', 'Tijjani Reijnders (Manchester City)', 'Guus Til (PSV Eindhoven)', 'Quinten Timber (Marseille)', 'Mats Wieffer (Brighton & Hove Albion)']],
    ['前锋', ['Brian Brobbey (Sunderland)', 'Memphis Depay (Corinthians)', 'Cody Gakpo (Liverpool)', 'Justin Kluivert (Bournemouth)', 'Donyell Malen (AS Roma)', 'Crysencio Summerville (West Ham)', 'Wout Weghorst (Ajax)']],
  ]),
  norway: buildSquad([
    ['门将', ['Orjan Nyland (Sevilla)', 'Egil Selvik (Watford)', 'Sander Tangvik (HSV)']],
    ['后卫', ['Julian Ryerson (Borussia Dortmund)', 'Kristoffer Ajer (Brentford)', 'Leo Skiri Ostigard (Genoa)', 'David Møller Wolfe (Wolverhampton Wanderers)', 'Marcus Holmgren Pedersen (Torino)', 'Torbjorn Heggem (Bologna)', 'Fredrik Bjorkan (Bodo/Glimt)', 'Henrik Falchener (Viking)', 'Sondre Langas (Derby County)']],
    ['中场', ['Martin Odegaard (Arsenal)', 'Sander Berge (Fulham)', 'Patrick Berg (Bodo/Glimt)', 'Kristian Thorstvedt (Sassuolo)', 'Morten Thorsby (Cremonese)', 'Thelo Aasgaard (Rangers)', 'Andreas Schjelderup (Benfica)', 'Jens Petter Hauge (Bodo/Glimt)', 'Fredrik Aursnes (Benfica)']],
    ['前锋', ['Erling Haaland (Manchester City)', 'Alexander Sorloth (Atletico Madrid)', 'Jorgen Strand Larsen (Crystal Palace)', 'Oscar Bobb (Fulham)', 'Antonio Nusa (RB Leipzig)']],
  ]),
  spain: buildSquad([
    ['门将', ['Unai Simon (Athletic Bilbao)', 'David Raya (Arsenal)', 'Joan Garcia (Barcelona)']],
    ['后卫', ['Marc Cucurella (Chelsea)', 'Alejandro Grimaldo (Bayer Leverkusen)', 'Pau Cubarsi (Barcelona)', 'Aymeric Laporte (Athletic Bilbao)', 'Marc Pubill (Atletico Madrid)', 'Eric Garcia (Barcelona)', 'Marcos Llorente (Atletico Madrid)', 'Pedro Porro (Tottenham Hotspur)']],
    ['中场', ['Pedri (Barcelona)', 'Fabian Ruiz (PSG)', 'Martin Zubimendi (Arsenal)', 'Gavi (Barcelona)', 'Rodri (Manchester City)', 'Alex Baena (Atletico Madrid)', 'Mikel Merino (Spain)']],
    ['前锋', ['Mikel Oyarzabal (Real Sociedad)', 'Dani Olmo (Barcelona)', 'Nico Williams (Athletic Bilbao)', 'Yeremy Pino (Crystal Palace)', 'Ferran Torres (Barcelona)', 'Borja Iglesias (Celta de Vigo)', 'Victor Munoz (Osasuna)', 'Lamine Yamal (Barcelona)']],
  ]),
  usa: buildSquad([
    ['门将', ['Chris Brady (Chicago Fire)', 'Matt Freese (New York City FC)', 'Matt Turner (New England Revolution)']],
    ['后卫', ['Max Arfsten (Columbus Crew)', 'Sergino Dest (PSV)', 'Alex Freeman (Villarreal)', 'Mark McKenzie (Toulouse)', 'Tim Ream (Charlotte FC)', 'Chris Richards (Crystal Palace)', 'Antonee Robinson (Fulham)', 'Miles Robinson (FC Cincinnati)', 'Joe Scally (Borussia Monchengladbach)', 'Auston Trusty (Celtic)']],
    ['中场', ['Brenden Aaronson (Leeds United)', 'Tyler Adams (AFC Bournemouth)', 'Sebastian Berhalter (Vancouver Whitecaps)', 'Weston McKennie (Juventus)', 'Christian Pulisic (AC Milan)', 'Gio Reyna (Borussia Monchengladbach)', 'Cristian Roldan (Seattle Sounders)', 'Malik Tillman (Bayer Leverkusen)', 'Tim Weah (Marseille)', 'Alejandro Zendejas (Club America)']],
    ['前锋', ['Folarin Balogun (AS Monaco)', 'Ricardo Pepi (PSV)', 'Haji Wright (Coventry City)']],
  ]),
};
